### ISSUE TITLE
複数台のNature Remo設定について

### ISSUE THREAD

**Issue by takamasa-arch** [kmaehashi/homebridge-nature-remo-cloud-aircon#24]
複数台のNature Remoの設定の場合はappliace_idを入れるようにとなっていますが、以下のように入れてみても、ログ上エラーとなってしまいました。
                {
                        "accessory": "NatureRemoAircon",
                        "name": "Air Conditioner",
                        "access_token": "ACCESS_TOKEN",
                        "appliance_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx"
                }

[2020-2-1 2:24:58 PM] [Air Conditioner] Target aircon could not be found. You can leave `appliance_id` blank to automatically use the first aircon.
.......
[2020-2-1 2:25:05 PM] TypeError: Cannot read property 'settings' of null
    at NatureRemoAircon.getTargetTemperature (/home/pi/node_modules/homebridge-nature-remo-cloud-aircon/index.js:270:22)
    at Characteristic.TargetTemperature.emit (events.js:198:13)
    at Characteristic.TargetTemperature.Characteristic.getValue (/home/pi/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/home/pi/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._handleGetCharacteristics (/home/pi/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:198:13)
    at HAPServer._handleCharacteristics (/home/pi/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/home/pi/.nvm/versions/node/v10.16.0/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:198:13)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

また複数台のNature Remo&エアコンをそれぞれに設定することは本プラグイン ではサポートしてないのでしょうか？もし設定できる場合、Config.jsonはどう書けばいいんでしょうか？

**Comment by takamasa-arch** [comment]
appliace_idの抜き取り部分に間違いがありましたので、そこを修正したら直りましたので、本件Closeします。
