### ISSUE TITLE
TypeErrorが出てしまいます。

### ISSUE THREAD

**Issue by D-Moriyama** [kmaehashi/homebridge-nature-remo-cloud-aircon#25]
こんにちは。
homebridge-dyson-linkとの併用にて、下記のエラーが出てしまいました。
解決策をご教授いただけませんでしょうか？

```
[2020/4/16 13:58:23] TypeError: Cannot read property 'settings' of null
    at NatureRemoAircon.getHeatingCoolingState (/usr/local/lib/node_modules/homebridge-nature-remo-aircon/index.js:315:34)
    at Characteristic.CurrentHeatingCoolingState.emit (events.js:189:13)
    at Characteristic.CurrentHeatingCoolingState.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:189:13)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:189:13)
```

なお、config.jsonは下記のとおりです。
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "MACアドレス",
		"port": 51826,
		"pin": "031-45-154"
	},

	"accessories": [{
			"accessory": "NatureRemoAircon",
			"name": "エアコン",
			"access_token": トークン",
			"appliance_id": "",
			"debug": true,
			"skip_command_request_if_no_change": true
		}
		
	],


	"platforms": [
		{
		"platform": "DysonPlatform",
		"name": "DysonPlatform",
		"email": "DysonのEメールアドレス",
		"password": "Dysonのパスワード",
		"country": "JP",
		"accessories": [
			{
			"ip": "IPアドレス",
			"displayName": "Dyson Pure Cool",
			"serialNumber": "シリアル番号",
			"nightModeVisible": true,
			"focusModeVisible": true,
			"autoModeVisible": true
		}
		],
		"plugin_map": [{
			"plgin_name": "homebridge-nature-remo-aircon"
			},
			{
			"plugin_name": "homebridge-dyson-link"
			}]
		}
	]
}
```

あと一歩のところでつまづいています。
よろしくお願いします。

**Comment by RickyPark** [comment]
homebridge-dyson-linkと関係なく同じエラーが出ています。

config.json

```json
```
error log
```javascript
Loading logs using native method...
File: /var/lib/homebridge/homebridge.log

[5/6/2020, 20:30:29] [センサー] NatureRemo Init
[5/6/2020, 20:30:29] [センサー] > [Schedule]
[5/6/2020, 20:30:29] [センサー] >> [request]
[5/6/2020, 20:30:29] [センサー] start homebridge Server センサー
Setup Payload:
X-HM://0024MCYSX2N0L
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 695-83-153 │     
    └────────────┘     
                       
[5/6/2020, 20:30:29] Homebridge is running on port 51438.
[5/6/2020, 20:30:30] [センサー] >>> [Update] temperature => 26.79
[5/6/2020, 20:30:30] [センサー] >>> [Update] humidity => 51
[5/6/2020, 20:30:30] TypeError: Cannot read property 'range' of null
    at NatureRemoAircon._getAllTemperatures (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:361:38)
    at NatureRemoAircon.getMaxTargetTemperature (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:353:32)
    at NatureRemoAircon._notifyConfigurationIfNeeded (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:170:22)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:122:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
[5/6/2020, 20:30:30] Got SIGTERM, shutting down Homebridge...
[5/6/2020, 20:30:31] TypeError: Cannot read property 'button' of null
    at NatureRemoAircon._translateHeatingCoolingState (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:209:18)
    at NatureRemoAircon._notifyLatestValues (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:196:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:160:12)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
[5/6/2020, 20:30:35] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/6/2020, 20:30:40] [HB Supervisor] Restarting Homebridge...
[5/6/2020, 20:30:40] [HB Supervisor] Starting Homebridge with extra flags: -I
[5/6/2020, 20:30:40] [HB Supervisor] Started Homebridge v1.0.4 with PID: 3664
[5/6/2020, 20:30:42] Loaded config.json with 2 accessories and 1 platforms.
[5/6/2020, 20:30:42] ---
[5/6/2020, 20:30:43] Loaded plugin: homebridge-config-ui-x
[5/6/2020, 20:30:43] Registering platform 'homebridge-config-ui-x.config'
[5/6/2020, 20:30:43] ---
[5/6/2020, 20:30:43] Loaded plugin: homebridge-nature-remo-cloud-aircon
[5/6/2020, 20:30:43] Plugin 'homebridge-nature-remo-cloud-aircon' tried to register with an incorrect plugin identifier: 'homebridge-nature-remo-aircon'. Please report this to the developer!
[5/6/2020, 20:30:43] Registering accessory 'homebridge-nature-remo-cloud-aircon.NatureRemoAircon'
[5/6/2020, 20:30:43] ---
[5/6/2020, 20:30:44] Loaded plugin: homebridge-nature-remo-sensor
[5/6/2020, 20:30:44] Registering accessory 'homebridge-nature-remo-sensor.remo-sensor'
[5/6/2020, 20:30:44] ---
[5/6/2020, 20:30:44] Loaded plugin: homebridge-nremo
[5/6/2020, 20:30:44] Registering accessory 'homebridge-nremo.NatureRemo'
[5/6/2020, 20:30:44] ---
[5/6/2020, 20:30:44] Loading 1 platforms...
[5/6/2020, 20:30:44] [Config] Initializing config platform...
[5/6/2020, 20:30:44] [Config] Running in Service Mode
[5/6/2020, 20:30:44] Loading 2 accessories...
[5/6/2020, 20:30:44] [リビングエアコン] Initializing NatureRemoAircon accessory...
[5/6/2020, 20:30:44] [センサー] Initializing remo-sensor accessory...
[5/6/2020, 20:30:44] [センサー] homebridge API version: 2.5
[5/6/2020, 20:30:44] [センサー] NatureRemo Init
[5/6/2020, 20:30:44] [センサー] > [Schedule]
[5/6/2020, 20:30:44] [センサー] >> [request]
[5/6/2020, 20:30:44] [センサー] start homebridge Server センサー
Setup Payload:
X-HM://0024MCYSX2N0L
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 695-83-153 │     
    └────────────┘     
                       
[5/6/2020, 20:30:44] Homebridge is running on port 51438.
[5/6/2020, 20:30:45] [センサー] >>> [Update] temperature => 26.79
[5/6/2020, 20:30:45] [センサー] >>> [Update] humidity => 51
[5/6/2020, 20:30:45] TypeError: Cannot read property 'range' of null
    at NatureRemoAircon._getAllTemperatures (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:361:38)
    at NatureRemoAircon.getMaxTargetTemperature (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:353:32)
    at NatureRemoAircon._notifyConfigurationIfNeeded (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:170:22)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:122:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
[5/6/2020, 20:30:45] Got SIGTERM, shutting down Homebridge...
[5/6/2020, 20:30:46] TypeError: Cannot read property 'button' of null
    at NatureRemoAircon._translateHeatingCoolingState (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:209:18)
    at NatureRemoAircon._notifyLatestValues (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:196:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:160:12)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
[5/6/2020, 20:30:50] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

**Comment by RickyPark** [comment]
こんにちは。
homebridge-dyson-linkと関係なく同じエラーが出るようです。

再現環境
raspberry pi 3B+
https://github.com/homebridge/homebridge-raspbian-image

config.json

```json
{
    "bridge": {
        "name": "Homebridge B1EA",
        "username": `userName`,
        "port": 51438,
        "pin": "695-83-153"
    },
    "accessories": [
        {
            "accessory": "NatureRemoAircon",
            "name": "リビングエアコン",
            "access_token": `accessToken`,
            "appliance_id": `applianceID`,
            "skip_command_request_if_no_change": true
        },
        {
            "accessory": "remo-sensor",
            "name": "センサー",
            "deviceName": "YuRi-Remo",
            "mini": false,
            "schedule": "*/5 * * * *",
            "accessToken": `accessToken`,
            "sensors": {
                "temperature": true,
                "humidity": true,
                "light": false
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "en",
            "platform": "config"
        }
    ]
}
```
error log
```javascript
Loading logs using native method...
File: /var/lib/homebridge/homebridge.log

[5/6/2020, 20:30:29] [センサー] NatureRemo Init
[5/6/2020, 20:30:29] [センサー] > [Schedule]
[5/6/2020, 20:30:29] [センサー] >> [request]
[5/6/2020, 20:30:29] [センサー] start homebridge Server センサー
Setup Payload:
X-HM://0024MCYSX2N0L
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 695-83-153 │     
    └────────────┘     
                       
[5/6/2020, 20:30:29] Homebridge is running on port 51438.
[5/6/2020, 20:30:30] [センサー] >>> [Update] temperature => 26.79
[5/6/2020, 20:30:30] [センサー] >>> [Update] humidity => 51
[5/6/2020, 20:30:30] TypeError: Cannot read property 'range' of null
    at NatureRemoAircon._getAllTemperatures (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:361:38)
    at NatureRemoAircon.getMaxTargetTemperature (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:353:32)
    at NatureRemoAircon._notifyConfigurationIfNeeded (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:170:22)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:122:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
[5/6/2020, 20:30:30] Got SIGTERM, shutting down Homebridge...
[5/6/2020, 20:30:31] TypeError: Cannot read property 'button' of null
    at NatureRemoAircon._translateHeatingCoolingState (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:209:18)
    at NatureRemoAircon._notifyLatestValues (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:196:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:160:12)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
[5/6/2020, 20:30:35] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/6/2020, 20:30:40] [HB Supervisor] Restarting Homebridge...
[5/6/2020, 20:30:40] [HB Supervisor] Starting Homebridge with extra flags: -I
[5/6/2020, 20:30:40] [HB Supervisor] Started Homebridge v1.0.4 with PID: 3664
[5/6/2020, 20:30:42] Loaded config.json with 2 accessories and 1 platforms.
[5/6/2020, 20:30:42] ---
[5/6/2020, 20:30:43] Loaded plugin: homebridge-config-ui-x
[5/6/2020, 20:30:43] Registering platform 'homebridge-config-ui-x.config'
[5/6/2020, 20:30:43] ---
[5/6/2020, 20:30:43] Loaded plugin: homebridge-nature-remo-cloud-aircon
[5/6/2020, 20:30:43] Plugin 'homebridge-nature-remo-cloud-aircon' tried to register with an incorrect plugin identifier: 'homebridge-nature-remo-aircon'. Please report this to the developer!
[5/6/2020, 20:30:43] Registering accessory 'homebridge-nature-remo-cloud-aircon.NatureRemoAircon'
[5/6/2020, 20:30:43] ---
[5/6/2020, 20:30:44] Loaded plugin: homebridge-nature-remo-sensor
[5/6/2020, 20:30:44] Registering accessory 'homebridge-nature-remo-sensor.remo-sensor'
[5/6/2020, 20:30:44] ---
[5/6/2020, 20:30:44] Loaded plugin: homebridge-nremo
[5/6/2020, 20:30:44] Registering accessory 'homebridge-nremo.NatureRemo'
[5/6/2020, 20:30:44] ---
[5/6/2020, 20:30:44] Loading 1 platforms...
[5/6/2020, 20:30:44] [Config] Initializing config platform...
[5/6/2020, 20:30:44] [Config] Running in Service Mode
[5/6/2020, 20:30:44] Loading 2 accessories...
[5/6/2020, 20:30:44] [リビングエアコン] Initializing NatureRemoAircon accessory...
[5/6/2020, 20:30:44] [センサー] Initializing remo-sensor accessory...
[5/6/2020, 20:30:44] [センサー] homebridge API version: 2.5
[5/6/2020, 20:30:44] [センサー] NatureRemo Init
[5/6/2020, 20:30:44] [センサー] > [Schedule]
[5/6/2020, 20:30:44] [センサー] >> [request]
[5/6/2020, 20:30:44] [センサー] start homebridge Server センサー
Setup Payload:
X-HM://0024MCYSX2N0L
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 695-83-153 │     
    └────────────┘     
                       
[5/6/2020, 20:30:44] Homebridge is running on port 51438.
[5/6/2020, 20:30:45] [センサー] >>> [Update] temperature => 26.79
[5/6/2020, 20:30:45] [センサー] >>> [Update] humidity => 51
[5/6/2020, 20:30:45] TypeError: Cannot read property 'range' of null
    at NatureRemoAircon._getAllTemperatures (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:361:38)
    at NatureRemoAircon.getMaxTargetTemperature (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:353:32)
    at NatureRemoAircon._notifyConfigurationIfNeeded (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:170:22)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:122:14)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
[5/6/2020, 20:30:45] Got SIGTERM, shutting down Homebridge...
[5/6/2020, 20:30:46] TypeError: Cannot read property 'button' of null
    at NatureRemoAircon._translateHeatingCoolingState (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:209:18)
    at NatureRemoAircon._notifyLatestValues (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:196:25)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:160:12)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
[5/6/2020, 20:30:50] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

宜しくお願いします。

**Comment by nimula** [comment]
同じのエラー発生しました、解決策をご教授いただけませんか？

**Comment by kmaehashi** [comment]
v1.1.0 をリリースしましたのでそちらで試してみていただけますか？

**Comment by RickyPark** [comment]
ありがとうございます。連休中に試してみたいと思います。よろしくお願いします。

**Comment by RickyPark** [comment]
テストできました、問題ありません。ありがとうございます！
