### ISSUE TITLE
Error after setting

### ISSUE THREAD

**Issue by hbkmanbass** [kmaehashi/homebridge-nature-remo-cloud-aircon#28]
Dear users, 

I got an error after install and I can't use my devices 

Please help me, thanks in advance

[18/02/2021, 17:47:18] Homebridge is running on port 51243.
[18/02/2021, 17:47:18] [室温センサー] >>> [Error] "Error: 401"
[18/02/2021, 17:47:18] [エアコン] failed to parse response: {"code":401001,"message":"Unauthorized"}
[18/02/2021, 17:47:43] [Homebridge UI] Starting terminal session
[18/02/2021, 17:47:50] [Homebridge UI] Terminal session ended.
[18/02/2021, 17:48:00] [エアコン] refreshing target appliance record
[18/02/2021, 17:48:00] [エアコン] failed to parse response: {"code":401001,"message":"Unauthorized"}
[18/02/2021, 17:49:00] [エアコン] refreshing target appliance record
[18/02/2021, 17:49:00] [エアコン] failed to parse response: {"code":401001,"message":"Unauthorized"}
[18/02/2021, 17:49:03] [室温センサー] > [Getting] temperature
[18/02/2021, 17:49:03] [室温センサー] >> [request]
[18/02/2021, 17:49:04] TypeError: Cannot read property 'settings' of null
    at NatureRemoAircon.getHeatingCoolingState (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:315:34)
    at CurrentHeatingCoolingState.emit (events.js:315:20)
    at CurrentHeatingCoolingState.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at CurrentHeatingCoolingState.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1145:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12

**Comment by kmaehashi** [comment]
Please make sure that `access_token` is correctly specified in config (esp. note that not `accessToken`).
