### ISSUE TITLE
Target Temperature error?

### ISSUE THREAD

**Issue by kinander** [kmaehashi/homebridge-nature-remo-cloud-aircon#33]
This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read properties of null (reading 'settings'). See https://homebridge.io/w/JtMGR for more info.

**Comment by kmaehashi** [comment]
Please provide the debug log by running `homebridge -D`.

**Comment by georz** [comment]
Hi!

My debug log is below. Please check them.
I think it started happening after I ran "apt full-upgrade" on my Raspberry Pi OS (Bookworm 64bit) yesterday.
```
[13/03/2024, 14:39:08] [homebridge-nature-remo-cloud-aircon] This plugin threw an error from the characteristic 'Current Heating Cooling State': Unhandled error thrown inside read handler for characteristic: Cannot read properties of null (reading 'settings'). See https://homebridge.io/w/JtMGR for more info.
[13/03/2024, 14:39:08] [homebridge-nature-remo-cloud-aircon] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside read handler for characteristic: Cannot read properties of null (reading 'settings'). See https://homebridge.io/w/JtMGR for more info.
[13/03/2024, 14:39:08] [homebridge-nature-remo-cloud-aircon] This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside read handler for characteristic: Cannot read properties of null (reading 'settings'). See https://homebridge.io/w/JtMGR for more info.
[13/03/2024, 14:39:08] [homebridge-nature-remo-cloud-aircon] This plugin threw an error from the characteristic 'Temperature Display Units': Unhandled error thrown inside read handler for characteristic: Cannot read properties of null (reading 'aircon'). See https://homebridge.io/w/JtMGR for more info.

[13/03/2024, 14:50:44] [仕事部屋エアコン] notifying TargetTemperature props: {"maxValue":32,"minValue":16,"minStep":1}
[13/03/2024, 14:50:44] [homebridge-nature-remo-cloud-aircon] Characteristic 'Target Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://homebridge.io/w/JtMGR for more info.
[13/03/2024, 14:50:44] [homebridge-nature-remo-cloud-aircon] Error: 
    at TargetTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at TargetTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2923:14)
    at TargetTemperature.Characteristic.setProps (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:35)
    at NatureRemoAircon._notifyConfigurationIfNeeded (/var/lib/homebridge/node_modules/homebridge-nature-remo-cloud-aircon/index.js:284:74)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nature-remo-cloud-aircon/index.js:117:14)
    at Object.emit (node:events:530:35)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-nature-remo-cloud-aircon/index.js:236:20)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
[13/03/2024, 14:50:44] [仕事部屋エアコン] notifying values: {"temp":"25","temp_unit":"c","mode":"warm","vol":"auto","dir":"","dirh":"","button":"power-off","updated_at":"2024-03-12T08:15:38Z"}
```

**Comment by tiger-git-hub** [comment]
I've encountered same situation.
Following log is mine.
`[04/05/2024, 16:37:28] [homebridge-nature-remo-cloud-aircon] This plugin generated a warning from the characteristic 'Target Heating Cooling State': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://homebridge.io/w/JtMGR for more info.
[04/05/2024, 16:37:28] [homebridge-nature-remo-cloud-aircon] Error: 
    at TargetHeatingCoolingState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3011:105)
    at TargetHeatingCoolingState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2862:14)
    at TargetHeatingCoolingState.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2328:20)
    at NatureRemoAircon._notifyLatestValues (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:306:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:130:12)
    at Object.emit (node:events:526:35)
    at Request._callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/index.js:264:20)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:514:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nature-remo-cloud-aircon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)`
